#!/bin/sh -ex

# Boiler plate code to print context of this script
juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

. inc/common

# If there is a config file already, PrestaShop is already installed & config'ed
if [ -f "$config_file_path" ]; then
	# TODO: Update the config file with new DB values even 
	#       if prestashop is alredy installed
	juju-log "PrestaShop is already setup, just silently going away"
	exit 0
fi

# Relation properties
database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

# Sanity checks
## If there is no database name defined, die
if [ -z "$database" ] ; then
    exit 0
fi

juju-log Config

sed -i "s|htmlspecialchars(\$this->database_server)|htmlspecialchars(\"$host\")|g" $install_path/install/theme/views/database.phtml
sed -i "s|htmlspecialchars(\$this->database_login)|htmlspecialchars(\"$user\")|g" $install_path/install/theme/views/database.phtml
sed -i "s|htmlspecialchars(\$this->database_password)|htmlspecialchars(\"$password\")|g" $install_path/install/theme/views/database.phtml
sed -i "s|htmlspecialchars(\$this->database_name)|htmlspecialchars(\"$database\")|g" $install_path/install/theme/views/database.phtml

# least access permissions for the configuration file
#chown www-data:www-data $config_file_path
#chmod 0640 $config_file_path

juju-log "Opening port 8080"
open-port 8080/tcp
