#!/bin/sh -ex

. inc/common

juju-log "Installing software"

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql pwgen zip unzip exim4-daemon-light


sed -i "s|dc_eximconfig_configtype=\'local\'|dc_eximconfig_configtype=\'internet\'|g" /etc/exim4/update-exim4.conf.conf

update-exim4.conf

a2enmod php5 headers
a2dissite 000-default
sed -i "s|max_execution_time = 30|max_execution_time = 600|g" /etc/php5/apache2/php.ini

service apache2 restart

juju-log "Download"

PRESTA_TARBALL="http://www.prestashop.com/ajax/controller.php?method=download&type=releases&file=prestashop_1.6.0.9.zip"

curl -vv -L $PRESTA_TARBALL > /tmp/prestashop.zip

juju-log "Extract"

mkdir -p $install_path
mkdir -p /tmp/prestashop
unzip /tmp/prestashop.zip prestashop/\* -d /tmp/prestashop
cp -fR /tmp/prestashop/prestashop/* $install_path


# Set better file permissions

set_permissions
