#!/bin/sh -ex

. inc/common

juju-log "Installing software"

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql pwgen zip unzip

a2enmod php5 headers
a2dissite 000-default

service apache2 restart

juju-log "Download"

PRESTA_TARBALL="http://www.prestashop.com/ajax/controller.php?method=download&type=releases&file=prestashop_1.6.0.9.zip"

curl -vv -L $PRESTA_TARBALL > /tmp/prestashop.zip

juju-log "Extract"

mkdir -p $install_path
unzip /tmp/prestashop.zip prestashop/\* -d $install_path

#rm -f /tmp/joomla.tar.gz
mv $install_path/prestashop/htaccess.txt $install_path/prestashop/.htaccess

#(
#patch -d $install_path -p1 < files/joomla/default_database.patch
#)

# Secret key for configuring Joomla
#secret_key=`pwgen 32 1`
#sed -i "s|public \$secret = '.*';|public \$secret = '"$secret_key"';|g" $install_path/installation/configuration.php-dist

# Set better file permissions
set_permissions
